version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Bogota"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Bogota"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5